[package]
name = "functional_pro"
version = "0.1.0"
authors = ["Vishal_Kumar_Sharma <vishalsharma16171718@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
